"""Erzeugt die Demodaten für Screenshots und das Demo-GIF. ALLE WERTE SIND ERFUNDEN.

Zwei Kategorien mit je drei Experimenten. RL-Controller (SAC, PPO, TD3) lernen über die Steps; klassische Regler
(LQR, PID, IK+PD) trainieren nicht: Sie haben trains=False und nur einen einzigen Messpunkt, also keinen Verlauf.

Aufruf gegen ein Backend mit LEERER Datenbank (nicht gegen deine echten Daten!):
    python docs/demo/generate_demo_data.py --api http://127.0.0.1:8001
"""

import argparse
import math
import random

import requests

TOTAL_STEPS = 1_000_000
LOG_EVERY = 10_000
SCENARIOS = {"nominal": 0.0, "mass+20%": 1.0, "sensor_noise": 0.8, "impulse": 1.2}

# Pro Controller: Lerngeschwindigkeit, Endniveau, Rechenzeit pro Step (s), Unruhe der Stellgröße,
# Empfindlichkeit gegenüber Störungen, Stellaufwand.
RL = {
    "SAC": {"speed": 5.0, "level": 0.97, "cost": 0.0024, "jitter": 0.10, "sensitivity": 0.08, "effort": 1.0},
    "PPO": {"speed": 2.2, "level": 0.93, "cost": 0.0007, "jitter": 0.22, "sensitivity": 0.10, "effort": 1.35},
    "TD3": {"speed": 3.8, "level": 0.95, "cost": 0.0020, "jitter": 0.14, "sensitivity": 0.12, "effort": 1.15},
}
# Test-Episode je Controller: Abklingrate und Kreisfrequenz des Regelfehlers
RESPONSE = {"SAC": (2.6, 5.0), "PPO": (1.5, 6.0), "TD3": (2.0, 4.4), "LQR": (3.4, 3.0), "PID": (1.8, 6.8), "IK+PD": (3.0, 4.0)}
HYPERPARAMETERS = {
    "SAC": {"learning_rate": 3e-4, "gamma": 0.99, "batch_size": 256, "net_arch": [256, 256]},
    "PPO": {"learning_rate": 3e-4, "gamma": 0.99, "n_steps": 2048, "clip_range": 0.2},
    "TD3": {"learning_rate": 1e-3, "gamma": 0.99, "policy_delay": 2, "target_noise": 0.2},
    "LQR": {"Q": "diag(10, 1, 10, 1)", "R": 0.1},
    "PID": {"Kp": 12.0, "Ki": 0.4, "Kd": 1.8},
    "IK+PD": {"Kp": 40.0, "Kd": 4.0},
}

EXPERIMENTS = [
    # Stabilisierung: klassische Regler sind nominal sehr gut, aber empfindlich gegenüber Störungen
    {"name": "Cart-pole balance", "environment": "CartPole-continuous-v1", "category": "stabilization",
     "difficulty": 0.00, "classical": {"LQR": (0.99, 0.30, 0.55), "PID": (0.95, 0.24, 0.70)}},
    {"name": "Ball balancer", "environment": "BallBalancer-v0", "category": "stabilization",
     "difficulty": 0.04, "classical": {"LQR": (0.97, 0.40, 0.60), "PID": (0.90, 0.30, 0.80)}},
    {"name": "Inverted pendulum", "environment": "InvertedPendulum-v4", "category": "stabilization",
     "difficulty": 0.02, "classical": {"LQR": (1.00, 0.28, 0.50), "PID": (0.96, 0.22, 0.65)}},
    # Positionierung: der klassische IK+PD-Regler ist schnell, aber bei Störungen deutlich schwächer
    {"name": "Reacher 2-DOF", "environment": "Reacher-v5", "category": "positioning",
     "difficulty": 0.03, "classical": {"IK+PD": (0.92, 0.35, 0.75)}},
    {"name": "Robot arm 3-DOF", "environment": "Arm3DOF-v0", "category": "positioning",
     "difficulty": 0.08, "classical": {"IK+PD": (0.85, 0.45, 0.85)}},
    {"name": "Drone to waypoint", "environment": "QuadrotorWaypoint-v0", "category": "positioning",
     "difficulty": 0.06, "classical": {"PID": (0.80, 0.50, 0.90)}},
]


def clamp(value: float) -> float:
    return max(0.0, min(1.0, value))


def trace(controller: str, jitter: float, rng: random.Random) -> list[dict]:
    """Test-Episode: Regelfehler schwingt gedämpft aus, zwei Stellgrößen regeln dagegen."""
    points = []
    noise = [0.0, 0.0]  # geglättetes Rauschen je Stellgröße, damit u nicht springt
    for i in range(250):
        t = i * 0.02
        decay, omega = RESPONSE[controller]
        error = 0.6 * math.exp(-decay * t) * math.cos(omega * t) + rng.gauss(0, 0.004 + jitter * 0.01)
        points.append({"signal": "error", "t": round(t, 3), "value": round(error, 5)})
        for axis in (0, 1):
            noise[axis] = 0.85 * noise[axis] + rng.gauss(0, jitter * 0.3)
            u = -1.4 * error * (1 if axis == 0 else 0.6) + noise[axis]
            points.append({"signal": f"u_{axis}", "t": round(t, 3), "value": round(max(-1, min(1, u)), 5)})
    return points


def post(api: str, path: str, body):
    res = requests.post(f"{api}{path}", json=body, timeout=60)
    res.raise_for_status()
    return res.json()


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--api", default="http://127.0.0.1:8001")
    api = parser.parse_args().api

    for spec in EXPERIMENTS:
        experiment = post(api, "/experiments", {
            "name": spec["name"], "environment": spec["environment"], "category": spec["category"],
            "description": "Demo data generated by docs/demo/generate_demo_data.py. All values are invented.",
        })
        rng = random.Random(spec["name"])
        difficulty = spec["difficulty"]

        # RL: fünf Seeds, Lernkurven über 1 Mio. Steps
        for controller, p in RL.items():
            for seed in range(5):
                speed = p["speed"] * rng.uniform(0.7, 1.3) * (1 - 2 * difficulty)
                level = clamp(p["level"] - difficulty + rng.gauss(0, 0.015))
                cost = p["cost"] * rng.uniform(0.85, 1.15)
                metrics = []
                for step in range(0, TOTAL_STEPS + 1, LOG_EVERY):
                    progress = 1 - math.exp(-speed * step / TOTAL_STEPS)
                    time = round(step * cost, 2)
                    success = clamp(level * progress + rng.gauss(0, 0.018))
                    metrics += [
                        {"name": "success_rate", "step": step, "value": round(success, 4), "time": time},
                        {"name": "episode_reward", "step": step, "value": round(-900 + 780 * progress + rng.gauss(0, 18), 2), "time": time},
                        {"name": "control_effort", "step": step, "value": round(p["effort"] * (2.2 - progress) * 10 + rng.gauss(0, 0.4), 3), "time": time},
                    ]
                run = post(api, "/runs", {
                    "experiment_id": experiment["id"], "controller": controller, "name": f"{controller} default",
                    "seed": seed, "reward": metrics[-2]["value"], "hyperparameters": HYPERPARAMETERS[controller],
                    "stability_time": round(rng.uniform(0.6, 1.8), 2) if level > 0.8 else None,
                    "num_steps": TOTAL_STEPS, "duration": round(TOTAL_STEPS * cost, 1),
                })
                post(api, f"/runs/{run['id']}/metrics", metrics)
                post(api, f"/runs/{run['id']}/evaluations", [
                    {"scenario": s, "name": "success_rate", "value": round(clamp(level - p["sensitivity"] * d + rng.gauss(0, 0.02)), 3)}
                    for s, d in SCENARIOS.items()
                ] + [{"name": "control_effort", "value": round(p["effort"] * 12 * rng.uniform(0.95, 1.05), 2)}])
                if seed == 0:
                    post(api, f"/runs/{run['id']}/traces", trace(controller, p["jitter"], rng))

        # Klassisch: ein Run, trains=False, genau ein Messpunkt, kein Verlauf
        for controller, (nominal, sensitivity, effort_factor) in spec["classical"].items():
            run = post(api, "/runs", {
                "experiment_id": experiment["id"], "controller": controller, "name": controller, "trains": False,
                "seed": 0, "reward": round(-120 - 300 * (1 - nominal), 1), "hyperparameters": HYPERPARAMETERS[controller],
                "stability_time": round(rng.uniform(0.4, 0.9), 2), "num_steps": 0, "duration": round(rng.uniform(2, 6), 1),
            })
            post(api, f"/runs/{run['id']}/metrics", [
                {"name": "success_rate", "step": 0, "value": nominal, "time": 0.0},
                {"name": "control_effort", "step": 0, "value": round(12 * effort_factor, 2), "time": 0.0},
            ])
            post(api, f"/runs/{run['id']}/evaluations", [
                {"scenario": s, "name": "success_rate", "value": round(clamp(nominal - sensitivity * d), 3)}
                for s, d in SCENARIOS.items()
            ] + [{"name": "control_effort", "value": round(12 * effort_factor, 2)}])
            post(api, f"/runs/{run['id']}/traces", trace(controller, 0.01, rng))

        print(f"{spec['name']}: angelegt")


if __name__ == "__main__":
    main()
